### ISSUE TITLE
Automatization

### ISSUE THREAD

**Issue by d-koppenhagen** [homescreenrocks/homescreen#10]
We should use an automatization tool to define some tasks like:
- [ ] use a default config
- [x] Mac OSX
   - [x] start backend and serve frontend
   - [ ] minify, uglify code and create map-files
   * [x] initial setup (maybe with example data)
   * [ ] run tests
- [x] MS Windows
   - [x] start backend and serve frontend
   - [ ] minify, uglify code and create map-files
   * [x] initial setup (maybe with example data)
   * [ ] run tests

**Comment by rommon** [comment]
closed in favor of #37
