### ISSUE TITLE
Edit function in backend doesn't work

### ISSUE THREAD

**Issue by d-koppenhagen** [homescreenrocks/homescreen#21]
I just realized, that the edit function in backend for items doesn't work.
Can you find the error @TilmannBach ? https://github.com/homescreenrocks/homescreen/blob/master/backend/routes/shoppinglist.js#L106,L116
I thought that I override the old object in the database, but it seems not like that.

**Comment by TilmannBach** [comment]
issue not applicable to new homescreen backend
