### ISSUE TITLE
integrate redis as datastore

### ISSUE THREAD

**Issue by rommon** [homescreenrocks/homescreen#33]
it also enables a pub/sub system for communication between our components. not sure if it is suitable for environments like a raspi.

* maybe also the settings should be stored in this store

**Comment by d-koppenhagen** [comment]
is this a data store for backend?

**Comment by rommon** [comment]
the data store is a core "module" in the backend to store the data of other modules, and also core components.

**Comment by TilmannBach** [comment]
you should give it a try

**Comment by TilmannBach** [comment]
invalid in new go version
