### ISSUE TITLE
Plugin library for easy usage of backend functions

### ISSUE THREAD

**Issue by TilmannBach** [homescreenrocks/homescreen#38]

**Comment by svenwltr** [comment]
@TilmannBach Where should that library go to? I suggest an own repo, because then we are able to tag it and use http://labix.org/gopkg.in. This would lower the obstacles for plugin developers.

**Comment by TilmannBach** [comment]
well this sounds great. I could setup such a repository.

**Comment by TilmannBach** [comment]
https://github.com/homescreenrocks/plugin-library 

* we should discuss this library on the issue tracker of the newly created repo
